### ISSUE TITLE
Ensure all benchmark_ids contained in:

### ISSUE THREAD

**Issue by SStolzman** [AZASRS/AZASRS#27]
fund_info <- AZASRS::get_pm_fund_info(add_benchmark = T)

are available in:
AZASRS::get_benchmark_daily_index(con = con)

**Comment by SStolzman** [comment]
I believe I solved most of your issue, however, it raised one with the input that @kwazasrs and I will have to figure out. Basically, there are 2 errors that show up in the check you desire, "Russell 2000" and "". There will never be an `NA` assigned as an index in the database, you could simply attach `""` manually if you need to. `Russell 2000` is slightly more complicated. The way the benchmark data comes in does not have a `benchmark_id` type of identifier, instead it has a `benchmark_description` ... due to the fact that `benchmark_description` does not have to be unique (whereas `benchmark_id` must be unique)... we are capturing the index under `RTY` and within `fund_info` we are seeing `Russell 2000` .

We'll put this as a high priority item and get it fixed, thanks for bringing it up.

Difference between data in R
```
> setdiff(required_benchmarks, available_benchmarks)
[1] "Russell 2000" ""  
```

Query from database, you'll notice that there is `RTY` associated, so is `Russell 2000` and only `RTY` is within index (we must choose one and not both).  
![Screen Shot 2020-01-24 at 10 01 43 AM](https://user-images.githubusercontent.com/40039153/73087956-8ec96f00-3e90-11ea-948c-d3d6643a496f.png)


### Here is what I believe you are looking for:
```
library('tidyverse')
library('AZASRS')

# SET ALL constants & immutable variables to be used at top of script
# Setting date restraints is important because bench data goes back to the 1970's
BENCH_START_DATE = '2003-09-30'
BENCH_END_DATE = get_value_date()
con = AZASRS_DATABASE_CONNECTION()


fund_info = AZASRS::get_pm_fund_info(add_benchmark = T)

# Get unique benchmarks into one vector
required_benchmarks <- AZASRS::get_pm_fund_info(add_benchmark = T, return_tibble = T) %>%
  select(PVT_Benchmark, SAA_Benchmark, IMP_Benchmark, Sector_Benchmark) %>%
  unlist() %>%
  unique() %>%
  unname() %>%
  replace_na("")

# Filter benchmark index for start date, end date, and ensure benchmarks are in the index
benchmark_index_data = get_benchmark_daily_index(all_bench_types = TRUE) %>%
  filter(effective_date >= BENCH_START_DATE, 
         effective_date <= BENCH_END_DATE,
         benchmark_id %in% required_benchmarks) %>%
  select(-benchmark_info_id) %>%
  as_tibble()

available_benchmarks = benchmark_index_data %>%
  select(benchmark_id) %>%
  unlist() %>%
  unique() %>%
  unname() %>%
  replace_na("")

setdiff(required_benchmarks, available_benchmarks)
required_benchmarks %in% available_benchmarks
```

### Other notes:  
This creates a tibble with all of these, we will likely run into problems with something like this in the future as new benchmarks are added beyond PVT, Sector, etc. due to the fact that these wind up being hard coded in and there is no good way to handle that dynamically. 

The reason this is so much code is due to the fact it has to line up with the new `pm_fund_info(add_benchmark = T)` .  If we can utilize joins rather than returning a list we could likely simplify this return and have the fund_id tied directly to the benchmark_id. This results in a longer tibble, but then it's simply a matter of filtering rather than searching through lists to match.

**Comment by MCopeland1** [comment]
Hi Scott,

I believe one problem with creating a single benchmark table is that the private market benchmarks data are prices and the benchmark data from SSBT are returns. For example, Russell 2000 will be in the table twice (1 with daily prices and 1 with daily/ monthly returns) but it appears its in the table 3 times.

Can you send the unique benchmark_ids to us for review?

**Comment by SStolzman** [comment]
The framework within the DB handles for this (I believe) there is a `benchmark_index` table and a `benchmark_daily_returns` table. One is in dollars, the other is the index values.

**Comment by SStolzman** [comment]
@John-Doran  and @MCopeland1 -- I added a bit of functionality to allow you to pull all unique benchmarks within the index table, you now simply add `all_bench_types = TRUE` as a parameter (shown below). Remember to run the install in order to get the features.

`devtools::install_github('AZASRS/AZASRS', force = TRUE)`

The command is now:
`get_benchmark_daily_index(all_bench_types = TRUE)`

@MCopeland1 - to get the unique benchmark_ids, the following should give it to you:
```
unique_bench_ids = get_benchmark_daily_index(all_bench_types = TRUE) %>%
  select(benchmark_id) %>% distinct() %>% 
  as_tibble()
```

**Comment by SStolzman** [comment]
Just as an FYI, this is for data related to fund_info, there are other benchmarks in the database, but those deal with publics, we need to ensure accuracy before this expands to cover those. It is a relatively minor move but I want to ensure all is accurate before pushing into the master branch

**Comment by SStolzman** [comment]
Would it make more sense to call this `get_pm_fund_benchmark_daily_index()` ?? while that is a long name, it may make a lot more sense when moving forward. Then, if necessary, we could change `get_benchmark_daily_index()` to include ALL benchmarks rather than those associated with private markets only.

**Comment by SStolzman** [comment]
Sorry to flood this, but @MCopeland1, ALL bench_ids can be found below.

```
all_bench_ids = tbl_benchmark_info() %>% 
  select(benchmark_id) %>% 
  distinct() %>% 
  as_tibble()
```

**Comment by SStolzman** [comment]
Kerry removed "Russell 2000" and replaced with "RTY"
